In [1]:
import pandas as pd

In [2]:
crime_data = pd.read_csv("Crime_Data_from_2020_to_Present.csv")

In [3]:
crime_data.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277

In [4]:
crime_data.tail(40)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
901317,231309462,04/20/2023 12:00:00 AM,04/20/2023 12:00:00 AM,900,13,Newton,1343,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,900 E JEFFERSON BL,NaN,34.0136,-118.2611
901318,230317497,10/02/2023 12:00:00 AM,10/01/2023 12:00:00 AM,2205,3,Southwest,361,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,5000 OBAMA BL,NaN,34.0215,-118.3515
901319,231014386,10/03/2023 12:00:00 AM,10/03/2023 12:00:00 AM,240,10,West Valley,1023,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,AA,Adult Arrest,236.0,NaN,NaN,NaN,19100 SHERMAN WY,NaN,34.2010,-118.5491
901320,231611415,08/21/2023 12:00:00 AM,08/04/2023 12:00:00 AM,1400,16,Foothill,1656,2,662,"BUNCO, GRAND THEFT",...,IC,Invest Cont,662.0,NaN,NaN,NaN,10300 QUILL AV,NaN,34.2561,-118.3166
901321,231314924,08/02/2023 12:00:00 AM,08/02/2023 12:00:00 AM,1432,13,Newton,1331,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2700 S GRAND AV,NaN,34.0254,-118.2729
901322,231225413,12/22/2023 12:00:00 AM,12/21/2023 12:00:00 AM,1600,12,77th Street,1268,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,BROADWAY,81ST ST,33.9659,-118.2783
901323,230509679,06/07/2023 12:00:00 AM,06/07/2023 12:00:00 AM,2045,5,Harbor,529,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,ANAHEIM ST,BANNING ST,33.7803,-118.2573
901324,231300825,06/07/2023 12:00:00 AM,06/07/2023 12:00:00 AM,2203,13,Newton,1322,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,2300 WALL ST,NaN,34.0254,-118.2629
901325,230908346,04/19/2023 12:00:00 AM,04/18/2023 12:00:00 AM,2243,9,Van Nuys,969,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,4800 COLDWATER CANYON AV,NaN,34.1576,-118.4138
901326,231608412,05/21/2023 12:00:00 AM,05/20/2023 12:00:00 AM,2130,16,Foothill,1663,2,624,BATTERY - SIMPLE ASSAULT,...,JA,Juv Arrest,624.0,NaN,NaN,NaN,12100 SHELDON ST,NaN,34.2374,-118.3964
901327,230512110,08/09/2023 12:00:00 AM,08/09/2023 12:00:00 AM,1310,5,Harbor,516,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,1200 N AVALON BL,NaN,33.7868,-118.2658
901328,230406516,03/19/2023 12:00:00 AM,03/19/2023 12:00:00 AM,122,4,Hollenbeck,488,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,3200 GARNET ST,NaN,34.0248,-118.2076
901329,230413421,10/15/2023 12:00:00 AM,10/15/2023 12:00:00 AM,2245,4,Hollenbeck,409,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,5100 E HUNTINGTON DR,NaN,34.0932,-118.1615
901330,230817019,11/18/2023 12:00:00 AM,11/18/2023 12:00:00 AM,100,8,West LA,859,1,310,BURGLARY,...,IC,Invest Cont,310.0,NaN,NaN,NaN,1600 S SHERBOURNE DR,NaN,34.0498,-118.3801
901331,230609209,05/01/2023 12:00:00 AM,04/29/2023 12:00:00 AM,600,6,Hollywood,639,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,1800 WINONA BL,NaN,34.1038,-118.3020
901332,230405171,02/05/2023 12:00:00 AM,02/02/2023 12:00:00 AM,1830,4,Hollenbeck,428,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,IC,Invest Cont,236.0,NaN,NaN,NaN,3000 BUDAU AV,NaN,34.0808,-118.1738
901333,231514016,08/27/2023 12:00:00 AM,08/27/2023 12:00:00 AM,30,15,N Hollywood,1548,1,761,BRANDISH WEAPON,...,AO,Adult Other,761.0,NaN,NaN,NaN,11000 MCCORMICK ST,NaN,34.1660,-118.3705
901334,230123693,11/09/2023 12:00:00 AM,11/09/2023 12:00:00 AM,1908,1,Central,159,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,JESSE ST,S SANTA FE AV,34.0365,-118.2292
901335,231321710,12/07/2023 12:00:00 AM,12/07/2023 12:00:00 AM,1245,13,Newton,1309,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,1500 MATEO ST,NaN,34.0266,-118.2322
901336,231007583,04/03/2023 12:00:00 AM,04/02/2023 12:00:00 AM,1600,10,West Valley,1031,1,310,BURGLARY,...,IC,Invest Cont,310.0,NaN,NaN,NaN,19500 VICTORY BL,NaN,34.1866,-118.5582
901337,230817177,11/22/2023 12:00:00 AM,11/10/2023 12:00:00 AM,1410,8,West LA,836,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2100 OVERLAND AV,NaN,34.0474,-118.4294
901338,231405429,02/05/2023 12:00:00 AM,02/05/2023 12:00:00 AM,1250,14,Pacific,1444,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,4300 LINCOLN BL,NaN,33.9846,-118.4428
901339,230612923,07/24/2023 12:00:00 AM,07/24/2023 12:00:00 AM,1400,6,Hollywood,638,1,210,ROBBERY,...,IC,Invest Cont,210.0,624.0,NaN,NaN,5500 HOLLYWOOD BL,NaN,34.1038,-118.3151
901340,230809415,05/10/2023 12:00:00 AM,05/10/2023 12:00:00 AM,1045,8,West LA,859,2,888,TRESPASSING,...,IC,Invest Cont,888.0,NaN,NaN,NaN,8500 HORNER ST,NaN,34.0499,-118.3762
901341,231609172,06/14/2023 12:00:00 AM,06/14/2023 12:00:00 AM,1207,16,Foothill,1684,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,8000 WEBB AV,NaN,34.2162,-118.3882
901342,230806871,03/03/2023 12:00:00 AM,03/02/2023 12:00:00 AM,620,8,West LA,889,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2000 S HOLT AV,NaN,34.0412,-118.3814
901343,231104474,01/12/2023 12:00:00 AM,01/12/2023 12:00:00 AM,1240,11,Northeast,1107,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440.0,NaN,NaN,NaN,1000 MILWAUKEE AV,NaN,34.1214,-118.1915
901344,230804266,01/08/2023 12:00:00 AM,01/08/2023 12:00:00 AM,1030,8,West LA,839,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,10200 SANTA MONICA BL,NaN,34.0611,-118.4184
901345,231510379,05/29/2023 12:00:00 AM,05/25/2023 12:00:00 AM,1100,15,N Hollywood,1548,2,662,"BUNCO, GRAND THEFT",...,IC,Invest Cont,662.0,NaN,NaN,NaN,5300 DENNY AV,NaN,34.1667,-118.3643
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,1800,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901347,231615006,12/15/2023 12:00:00 AM,12/14/2023 12:00:00 AM,1105,16,Foothill,1608,1,210,ROBBERY,...,AO,Adult Other,210.0,NaN,NaN,NaN,11000 FOOTHILL BL,NaN,34.2777,-118.3496
901348,231110961,07/09/2023 12:00:00 AM,07/06/2023 12:00:00 AM,1200,11,Northeast,1115,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,2000 MERTON AV,NaN,34.1381,-118.2115
901349,240904007,12/31/2023 12:00:00 AM,12/31/2023 12:00:00 AM,230,9,Van Nuys,952,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,AO,Adult Other,745.0,NaN,NaN,NaN,15300 WEDDINGTON ST,NaN,34.1667,-118.4662
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,1230,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901351,231604807,01/27/2023 12:00:00 AM,01/26/2023 12:00:00 AM,1800,16,Foothill,1663,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,12500 BRANFORD ST,NaN,34.2466,-118.4054
901352,231606525,03/22/2023 12:00:00 AM,03/22/2023 12:00:00 AM,1000,16,Foothill,1602,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,12800 FILMORE ST,NaN,34.2790,-118.4116
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,1000,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901354,230115220,07/02/2023 12:00:00 AM,07/01/2023 12:00:00 AM,1,1,Central,154,1,352,PICKPOCKET,...,IC,Invest Cont,352.0,NaN,NaN,NaN,500 S MAIN ST,NaN,34.0467,-118.2485
901355,230906458,03/05/2023 12:00:00 AM,03/05/2023 12:00:00 AM,900,9,Van Nuys,914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,14500 HARTLAND ST,NaN,34.1951,-118.4487
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,2300,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [5]:
z_area =(crime_data["AREA NAME"] == "").sum()

In [6]:
z_area

0

In [7]:
len(crime_data["AREA NAME"])

901357

In [8]:
crime_data["AREA NAME"].value_counts()

AREA NAME
Central        61416
77th Street    56381
Pacific        52537
Southwest      50654
Hollywood      47508
Southeast      45503
Olympic        45486
N Hollywood    45124
Newton         45032
Wilshire       43191
Rampart        42548
West LA        41300
Northeast      38810
Van Nuys       38056
West Valley    37857
Harbor         37086
Topanga        36814
Devonshire     36747
Mission        35849
Hollenbeck     33662
Foothill       29796
Name: count, dtype: int64

In [9]:
crime_data["AREA NAME"].value_counts(normalize = True)

AREA NAME
Central        0.068137
77th Street    0.062551
Pacific        0.058287
Southwest      0.056197
Hollywood      0.052707
Southeast      0.050483
Olympic        0.050464
N Hollywood    0.050062
Newton         0.049960
Wilshire       0.047918
Rampart        0.047204
West LA        0.045820
Northeast      0.043057
Van Nuys       0.042221
West Valley    0.042000
Harbor         0.041145
Topanga        0.040843
Devonshire     0.040769
Mission        0.039772
Hollenbeck     0.037346
Foothill       0.033057
Name: proportion, dtype: float64

In [10]:
most_crime_area = crime_data["AREA NAME"].value_counts(normalize = True)

In [11]:
most_crime_area.sort_values(ascending = False)

AREA NAME
Central        0.068137
77th Street    0.062551
Pacific        0.058287
Southwest      0.056197
Hollywood      0.052707
Southeast      0.050483
Olympic        0.050464
N Hollywood    0.050062
Newton         0.049960
Wilshire       0.047918
Rampart        0.047204
West LA        0.045820
Northeast      0.043057
Van Nuys       0.042221
West Valley    0.042000
Harbor         0.041145
Topanga        0.040843
Devonshire     0.040769
Mission        0.039772
Hollenbeck     0.037346
Foothill       0.033057
Name: proportion, dtype: float64

In [12]:
high_crime_areas =most_crime_area > 0.05 # make a boolean logic

In [13]:
high_crime_areas

AREA NAME
Central         True
77th Street     True
Pacific         True
Southwest       True
Hollywood       True
Southeast       True
Olympic         True
N Hollywood     True
Newton         False
Wilshire       False
Rampart        False
West LA        False
Northeast      False
Van Nuys       False
West Valley    False
Harbor         False
Topanga        False
Devonshire     False
Mission        False
Hollenbeck     False
Foothill       False
Name: proportion, dtype: bool

In [14]:
most_crime_area[high_crime_areas]

AREA NAME
Central        0.068137
77th Street    0.062551
Pacific        0.058287
Southwest      0.056197
Hollywood      0.052707
Southeast      0.050483
Olympic        0.050464
N Hollywood    0.050062
Name: proportion, dtype: float64

In [15]:
most_cr_bol = most_crime_area[high_crime_areas].index

In [16]:
most_cr = crime_data["AREA NAME"].isin(most_cr_bol)

In [17]:
most_cr

0         False
1          True
2          True
3         False
4          True
          ...
901352    False
901353     True
901354     True
901355    False
901356     True
Name: AREA NAME, Length: 901357, dtype: bool

In [18]:
crime_data[most_cr] #Here ,the data of most crime areas has been seperated from the rest.

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,1800,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,1230,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,1000,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901354,230115220,07/02/2023 12:00:00 AM,07/01/2023 12:00:00 AM,1,1,Central,154,1,352,PICKPOCKET,...,IC,Invest Cont,352.0,NaN,NaN,NaN,500 S MAIN ST,NaN,34.0467,-118.2485
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,2300,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [19]:
TCA = crime_data[most_cr] # TCA = Top Crime Areas

# Now we will find the which type of crime occur most in top crime areas ?

In [20]:
TCA.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620

In [21]:
TCA.rename(columns = {'Crm Cd Desc' :'Crime Name' })

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,1800,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,1230,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,1000,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901354,230115220,07/02/2023 12:00:00 AM,07/01/2023 12:00:00 AM,1,1,Central,154,1,352,PICKPOCKET,...,IC,Invest Cont,352.0,NaN,NaN,NaN,500 S MAIN ST,NaN,34.0467,-118.2485
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,2300,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [22]:
TCA = TCA.rename(columns = {'Crm Cd Desc' :'Crime Name' })

In [23]:
TCA

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,1800,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,1230,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,1000,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901354,230115220,07/02/2023 12:00:00 AM,07/01/2023 12:00:00 AM,1,1,Central,154,1,352,PICKPOCKET,...,IC,Invest Cont,352.0,NaN,NaN,NaN,500 S MAIN ST,NaN,34.0467,-118.2485
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,2300,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [24]:
TCA["Crime Name"].value_counts()

Crime Name
VEHICLE - STOLEN                                           41177
BATTERY - SIMPLE ASSAULT                                   34011
BURGLARY FROM VEHICLE                                      26794
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT             26643
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)    24564
                                                           ...
FIREARMS RESTRAINING ORDER (FIREARMS RO)                       2
THEFT, COIN MACHINE - ATTEMPT                                  2
MANSLAUGHTER, NEGLIGENT                                        2
BLOCKING DOOR INDUCTION CENTER                                 1
DISHONEST EMPLOYEE ATTEMPTED THEFT                             1
Name: count, Length: 138, dtype: int64

In [25]:
a=(TCA["Crime Name"] == "").sum() # to check if there are an empty string in Crime Names

In [26]:
a

0

In [27]:
TCA["Crime Name"].value_counts(normalize = True)

Crime Name
VEHICLE - STOLEN                                           0.101770
BATTERY - SIMPLE ASSAULT                                   0.084059
BURGLARY FROM VEHICLE                                      0.066222
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT             0.065849
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)    0.060710
                                                             ...
FIREARMS RESTRAINING ORDER (FIREARMS RO)                   0.000005
THEFT, COIN MACHINE - ATTEMPT                              0.000005
MANSLAUGHTER, NEGLIGENT                                    0.000005
BLOCKING DOOR INDUCTION CENTER                             0.000002
DISHONEST EMPLOYEE ATTEMPTED THEFT                         0.000002
Name: proportion, Length: 138, dtype: float64

In [28]:
Top_Crimes =TCA["Crime Name"].value_counts(normalize = True)

In [29]:
Top_C_log =Top_Crimes > 0.05

In [30]:
Top_Crimes[Top_C_log]

Crime Name
VEHICLE - STOLEN                                           0.101770
BATTERY - SIMPLE ASSAULT                                   0.084059
BURGLARY FROM VEHICLE                                      0.066222
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT             0.065849
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)    0.060710
THEFT OF IDENTITY                                          0.056141
THEFT PLAIN - PETTY ($950 & UNDER)                         0.054378
BURGLARY                                                   0.051615
INTIMATE PARTNER - SIMPLE ASSAULT                          0.050298
Name: proportion, dtype: float64

In [31]:
Top_Crimes=Top_Crimes[Top_C_log]

In [32]:
Top_Crimes.index  # These are the most type of crime occurs in top crime areas .

Index(['VEHICLE - STOLEN', 'BATTERY - SIMPLE ASSAULT', 'BURGLARY FROM VEHICLE',
       'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
       'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
       'THEFT OF IDENTITY', 'THEFT PLAIN - PETTY ($950 & UNDER)', 'BURGLARY',
       'INTIMATE PARTNER - SIMPLE ASSAULT'],
      dtype='object', name='Crime Name')

In [33]:
strt_77=(TCA["AREA NAME"] == "77th Street").sum()

#####

In [34]:
strt_77

56381

In [35]:
strt_77_df = TCA[TCA["AREA NAME"] == "77th Street"]

In [36]:
strt_77_df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
30,211209197,03/20/2021 12:00:00 AM,07/01/2020 12:00:00 AM,1425,12,77th Street,1243,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1600 W 67TH ST,NaN,33.9785,-118.3068
32,231207725,02/27/2023 12:00:00 AM,01/27/2020 12:00:00 AM,635,12,77th Street,1242,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,6200 4TH AV,NaN,33.9837,-118.3216
33,231205231,01/17/2023 12:00:00 AM,01/01/2020 12:00:00 AM,1535,12,77th Street,1268,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,100 E 85TH ST,NaN,33.9610,-118.2739
37,211220472,09/27/2021 12:00:00 AM,11/26/2020 12:00:00 AM,2000,12,77th Street,1259,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,AO,Adult Other,930.0,NaN,NaN,NaN,7800 S SAN PEDRO ST,NaN,33.9679,-118.2695
43,231210407,04/18/2023 12:00:00 AM,01/01/2020 12:00:00 AM,1,12,77th Street,1259,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,700 E 73RD ST,NaN,33.9739,-118.2630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901276,231223960,11/22/2023 12:00:00 AM,11/22/2023 12:00:00 AM,1345,12,77th Street,1283,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1500 W 98TH ST,NaN,33.9468,-118.3025
901281,231217487,08/11/2023 12:00:00 AM,08/11/2023 12:00:00 AM,1900,12,77th Street,1218,2,890,FAILURE TO YIELD,...,AA,Adult Arrest,890.0,NaN,NaN,NaN,VERMONT AV,54TH ST,33.9932,-118.2915
901306,231209545,04/04/2023 12:00:00 AM,04/04/2023 12:00:00 AM,910,12,77th Street,1233,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,1600 W 59TH ST,NaN,33.9875,-118.3046
901312,231212224,05/17/2023 12:00:00 AM,05/17/2023 12:00:00 AM,2300,12,77th Street,1268,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,8200 S MAIN ST,NaN,33.9654,-118.2739
901322,231225413,12/22/2023 12:00:00 AM,12/21/2023 12:00:00 AM,1600,12,77th Street,1268,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,BROADWAY,81ST ST,33.9659,-118.2783

In [37]:
strt_77_df["Crime Name"].value_counts(ascending = False) # Just to check what type of crime specifically occur in 77th street,

Crime Name
VEHICLE - STOLEN                                  7428
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT    5582
BATTERY - SIMPLE ASSAULT                          4431
THEFT OF IDENTITY                                 3990
INTIMATE PARTNER - SIMPLE ASSAULT                 3877
                                                  ...
GRAND THEFT / AUTO REPAIR                            1
DISHONEST EMPLOYEE - GRAND THEFT                     1
CONSPIRACY                                           1
COUNTERFEIT                                          1
INCITING A RIOT                                      1
Name: count, Length: 116, dtype: int64

# Now we will check at which time most crime occurs ?

In [38]:
TCA.head(20)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620
7,220314085,07/22/2022 12:00:00 AM,05/12/2020 12:00:00 AM,1110,3,Southwest,303,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
10,221804943,01/21/2022 12:00:00 AM,07/01/2020 12:00:00 AM,1335,18,Southeast,1822,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,100 W COLDEN AV,NaN,33.9492,-118.2739
16,230312288,06/01/2023 12:00:00 AM,02/02/2020 12:00:00 AM,315,3,Southwest,391,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,4200 SANTO TOMAS DR,NaN,34.0103,-118.3456
17,231805781,02/03/2023 12:00:00 AM,07/01/2020 12:00:00 AM,805,18,Southeast,1802,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,400 W 90TH ST,NaN,33.9551,-118.2814
25,232011098,06/04/2023 12:00:00 AM,07/01/2020 12:00:00 AM,1200,20,Olympic,2088,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,IC,Invest Cont,812.0,860.0,NaN,NaN,1700 S WESTMORELAND AV,NaN,34.0433,-118.2892
30,211209197,03/20/2021 12:00:00 AM,07/01/2020 12:00:00 AM,1425,12,77th Street,1243,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1600 W 67TH ST,NaN,33.9785,-118.3068
32,231207725,02/27/2023 12:00:00 AM,01/27/2020 12:00:00 AM,635,12,77th Street,1242,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,6200 4TH AV,NaN,33.9837,-118.3216
33,231205231,01/17/2023 12:00:00 AM,01/01/2020 12:00:00 AM,1535,12,77th Street,1268,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,100 E 85TH ST,NaN,33.9610,-118.2739
35,221404806,01/19/2022 12:00:00 AM,01/18/2020 12:00:00 AM,1600,14,Pacific,1446,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,WASHINGTON PL,INGLEWOOD,34.0022,-118.4255
37,211220472,09/27/2021 12:00:00 AM,11/26/2020 12:00:00 AM,2000,12,77th Street,1259,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,AO,Adult Other,930.0,NaN,NaN,NaN,7800 S SAN PEDRO ST,NaN,33.9679,-118.2695
38,211818877,10/22/2021 12:00:00 AM,03/10/2020 12:00:00 AM,1500,18,Southeast,1801,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,8700 ORCHARD AV,NaN,33.9587,-118.2882
39,221515929,10/10/2022 12:00:00 AM,04/01/2020 12:00:00 AM,1200,15,N Hollywood,1539,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,5700 CARTWRIGHT AV,NaN,34.1740,-118.3638
43,231210407,04/18/2023 12:00:00 AM,01/01/2020 12:00:00 AM,1,12,77th Street,1259,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,700 E 73RD ST,NaN,33.9739,-118.2630
45,221504294,01/06/2022 12:00:00 AM,10/30/2020 12:00:00 AM,1,15,N Hollywood,1535,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,AA,Adult Arrest,812.0,NaN,NaN,NaN,5700 COLFAX AV,NaN,34.1740,-118.3878
49,230610629,06/02/2023 12:00:00 AM,05/31/2020 12:00:00 AM,430,6,Hollywood,645,1,310,BURGLARY,...,IC,Invest Cont,310.0,NaN,NaN,NaN,1700 ORCHID AV,NaN,34.1030,-118.3402

In [39]:
import datetime as dt

In [40]:
TCA["TIME OCC"].info()

<class 'pandas.core.series.Series'>
Index: 404609 entries, 1 to 901356
Series name: TIME OCC
Non-Null Count   Dtype
--------------   -----
404609 non-null  int64
dtypes: int64(1)
memory usage: 6.2 MB

In [41]:
TCA["TIME OCC"].value_counts().head(24)

TIME OCC
1200    12744
1800     9987
2000     9522
1700     9446
2200     9128
1900     8926
2100     8658
1600     8134
1500     7906
1        7294
2300     7276
1400     7178
1000     6662
1300     6244
800      6123
1100     5952
900      5444
100      5121
1930     4395
1830     4389
200      4346
1730     4216
2030     4128
2130     4112
Name: count, dtype: int64

In [42]:
TCA["TIME OCC"].astype(str)

1         1800
2         1700
4         1200
5         2300
6          900
          ...
901346    1800
901350    1230
901353    1000
901354       1
901356    2300
Name: TIME OCC, Length: 404609, dtype: object

In [43]:
TCA["TIME OCC"].astype(str).str.len() ==4

1          True
2          True
4          True
5          True
6         False
          ...
901346     True
901350     True
901353     True
901354    False
901356     True
Name: TIME OCC, Length: 404609, dtype: bool

In [44]:
bol_time=TCA["TIME OCC"].astype(str).str.len() ==4

In [45]:
c_time=TCA["TIME OCC"]

In [46]:
c_time[bol_time]

1         1800
2         1700
4         1200
5         2300
7         1110
          ...
901345    1100
901346    1800
901350    1230
901353    1000
901356    2300
Name: TIME OCC, Length: 289170, dtype: int64

In [47]:
cc_time = c_time[bol_time]

In [48]:
TCA["TIME OCC"].isin(cc_time)

1          True
2          True
4          True
5          True
6         False
          ...
901346     True
901350     True
901353     True
901354    False
901356     True
Name: TIME OCC, Length: 404609, dtype: bool

In [49]:
cor_f_t=TCA["TIME OCC"].isin(cc_time)

In [50]:
TCA[cor_f_t]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
7,220314085,07/22/2022 12:00:00 AM,05/12/2020 12:00:00 AM,1110,3,Southwest,303,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901345,231510379,05/29/2023 12:00:00 AM,05/25/2023 12:00:00 AM,1100,15,N Hollywood,1548,2,662,"BUNCO, GRAND THEFT",...,IC,Invest Cont,662.0,NaN,NaN,NaN,5300 DENNY AV,NaN,34.1667,-118.3643
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,1800,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,1230,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,1000,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,2300,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [51]:
Time_Cor_TCA = TCA[cor_f_t]

In [52]:
pd.to_datetime(Time_Cor_TCA["TIME OCC"], format = '%H%M')

1        1900-01-01 18:00:00
2        1900-01-01 17:00:00
4        1900-01-01 12:00:00
5        1900-01-01 23:00:00
7        1900-01-01 11:10:00
                 ...
901345   1900-01-01 11:00:00
901346   1900-01-01 18:00:00
901350   1900-01-01 12:30:00
901353   1900-01-01 10:00:00
901356   1900-01-01 23:00:00
Name: TIME OCC, Length: 289170, dtype: datetime64[ns]

In [53]:
Time_Cor_TCA.loc[:,"TIME OCC"]=pd.to_datetime(Time_Cor_TCA["TIME OCC"], format = '%H%M')

In [54]:
Time_Cor_TCA

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1900-01-01 18:00:00,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1900-01-01 17:00:00,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1900-01-01 12:00:00,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,1900-01-01 23:00:00,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
7,220314085,07/22/2022 12:00:00 AM,05/12/2020 12:00:00 AM,1900-01-01 11:10:00,3,Southwest,303,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901345,231510379,05/29/2023 12:00:00 AM,05/25/2023 12:00:00 AM,1900-01-01 11:00:00,15,N Hollywood,1548,2,662,"BUNCO, GRAND THEFT",...,IC,Invest Cont,662.0,NaN,NaN,NaN,5300 DENNY AV,NaN,34.1667,-118.3643
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,1900-01-01 18:00:00,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,1900-01-01 12:30:00,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,1900-01-01 10:00:00,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,1900-01-01 23:00:00,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [55]:
Time_Cor_TCA.loc[:,["TIME OCC"]]=Time_Cor_TCA["TIME OCC"].dt.time

In [56]:
Time_Cor_TCA

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,18:00:00,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,17:00:00,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,12:00:00,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,23:00:00,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
7,220314085,07/22/2022 12:00:00 AM,05/12/2020 12:00:00 AM,11:10:00,3,Southwest,303,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901345,231510379,05/29/2023 12:00:00 AM,05/25/2023 12:00:00 AM,11:00:00,15,N Hollywood,1548,2,662,"BUNCO, GRAND THEFT",...,IC,Invest Cont,662.0,NaN,NaN,NaN,5300 DENNY AV,NaN,34.1667,-118.3643
901346,230126819,12/19/2023 12:00:00 AM,12/19/2023 12:00:00 AM,18:00:00,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,07/08/2023 12:00:00 AM,07/08/2023 12:00:00 AM,12:30:00,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,12/07/2023 12:00:00 AM,12/01/2023 12:00:00 AM,10:00:00,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901356,230319786,11/10/2023 12:00:00 AM,11/09/2023 12:00:00 AM,23:00:00,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [57]:
Time_Cor_TCA["TIME OCC"].value_counts()

TIME OCC
12:00:00    12744
18:00:00     9987
20:00:00     9522
17:00:00     9446
22:00:00     9128
            ...
23:32:00       11
22:39:00       11
22:51:00       11
22:29:00        9
22:31:00        7
Name: count, Length: 840, dtype: int64

# it has been found out that 6PM to 8PM , around 5PM and 12:00 Noon , they are the most dangerous time to visit in Top Crime Areas to visit.

In [58]:
Time_Cor_TCA.loc[:,"Date Rptd"]=Time_Cor_TCA["Date Rptd"].str.replace("AM" ,"")

In [59]:
Time_Cor_TCA.loc[:,"DATE OCC"]=Time_Cor_TCA["DATE OCC"].str.replace("AM" ,"")

In [60]:
pd.to_datetime(Time_Cor_TCA["Date Rptd"])

1        2020-02-09 12:00:00
2        2020-11-11 12:00:00
4        2022-08-18 12:00:00
5        2023-04-04 12:00:00
7        2022-07-22 12:00:00
                 ...
901345   2023-05-29 12:00:00
901346   2023-12-19 12:00:00
901350   2023-07-08 12:00:00
901353   2023-12-07 12:00:00
901356   2023-11-10 12:00:00
Name: Date Rptd, Length: 289170, dtype: datetime64[ns]

In [61]:
Time_Cor_TCA.loc[:,"Date Rptd"]=pd.to_datetime(Time_Cor_TCA["Date Rptd"])

In [62]:
pd.to_datetime(Time_Cor_TCA["DATE OCC"])

1        2020-02-08 12:00:00
2        2020-11-04 12:00:00
4        2020-08-17 12:00:00
5        2020-12-01 12:00:00
7        2020-05-12 12:00:00
                 ...
901345   2023-05-25 12:00:00
901346   2023-12-19 12:00:00
901350   2023-07-08 12:00:00
901353   2023-12-01 12:00:00
901356   2023-11-09 12:00:00
Name: DATE OCC, Length: 289170, dtype: datetime64[ns]

In [63]:
Time_Cor_TCA.loc[:,"DATE OCC"]=pd.to_datetime(Time_Cor_TCA["DATE OCC"])

In [64]:
Time_Cor_TCA # converted Date Rptd and DATE OCC coulns into datetype object

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crime Name,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,200106753,2020-02-09 12:00:00,2020-02-08 12:00:00,18:00:00,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,2020-11-11 12:00:00,2020-11-04 12:00:00,17:00:00,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
4,220614831,2022-08-18 12:00:00,2020-08-17 12:00:00,12:00:00,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,2023-04-04 12:00:00,2020-12-01 12:00:00,23:00:00,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
7,220314085,2022-07-22 12:00:00,2020-05-12 12:00:00,11:10:00,3,Southwest,303,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901345,231510379,2023-05-29 12:00:00,2023-05-25 12:00:00,11:00:00,15,N Hollywood,1548,2,662,"BUNCO, GRAND THEFT",...,IC,Invest Cont,662.0,NaN,NaN,NaN,5300 DENNY AV,NaN,34.1667,-118.3643
901346,230126819,2023-12-19 12:00:00,2023-12-19 12:00:00,18:00:00,1,Central,153,2,850,INDECENT EXPOSURE,...,IC,Invest Cont,850.0,NaN,NaN,NaN,600 S HILL ST,NaN,34.0473,-118.2531
901350,230115595,2023-07-08 12:00:00,2023-07-08 12:00:00,12:30:00,1,Central,111,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,800 BARTLETT ST,NaN,34.0626,-118.2445
901353,230618716,2023-12-07 12:00:00,2023-12-01 12:00:00,10:00:00,6,Hollywood,647,2,901,VIOLATION OF RESTRAINING ORDER,...,IC,Invest Cont,901.0,NaN,NaN,NaN,1500 N BRONSON AV,NaN,34.0980,-118.3180
901356,230319786,2023-11-10 12:00:00,2023-11-09 12:00:00,23:00:00,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,4100 S HOBART BL,NaN,34.0091,-118.3078

In [65]:
# Want to check if crime equally occurs to both men and women  ?

In [66]:
Time_Cor_TCA.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crime Name', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')

In [67]:
Time_Cor_TCA["Vict Sex"].value_counts()

Vict Sex
M    115827
F    106370
X     28542
H        28
-         1
Name: count, dtype: int64

In [68]:
Time_Cor_TCA["Vict Sex"].value_counts(normalize = True)

Vict Sex
M    0.461889
F    0.424177
X    0.113818
H    0.000112
-    0.000004
Name: proportion, dtype: float64

In [69]:
Time_Cor_TCA["Vict Age"].value_counts()

Vict Age
 0     70284
 30     6992
 29     6820
 28     6594
 31     6503
       ...
 96       19
 95       17
-1        14
-2         3
-4         3
Name: count, Length: 102, dtype: int64

In [70]:
import numpy as np

In [71]:
Time_Cor_TCA["Vict Age"].replace(0,np.nan)

1         47.0
2         19.0
4         28.0
5         41.0
7         27.0
          ...
901345    25.0
901346    64.0
901350    35.0
901353    30.0
901356    38.0
Name: Vict Age, Length: 289170, dtype: float64

In [77]:
Time_Cor_TCA.loc[:,"Vict Age"]=Time_Cor_TCA["Vict Age"].replace(0,np.nan)

In [78]:
Time_Cor_TCA["Vict Age"].dropna

<bound method Series.dropna of 1         47.0
2         19.0
4         28.0
5         41.0
7         27.0
          ...
901345    25.0
901346    64.0
901350    35.0
901353    30.0
901356    38.0
Name: Vict Age, Length: 289170, dtype: float64>

In [79]:
Time_Cor_TCA.loc[:,"Vict Age"].dropna=Time_Cor_TCA["Vict Age"].dropna

### Result/Suggestion= People should avoid visiting to Central , 77th Street, Pacific , Southwest,Hollywood from 5 to 8 PM and 12 Noon especially in vehicles. These are hot spots for crimes to happen.